name: " Documentaci贸n"
description: "Reporta errores o mejoras en la documentaci贸n de la landing page."
labels: ["documentation"]
title: "[] Documentaci贸n: <t铆tulo descriptivo>"
body:
  - type: markdown
    attributes:
      value: |
        Gracias por ayudar a mejorar la documentaci贸n 
        Por favor deja informaci贸n clara y breve para que podamos arreglarlo r谩pido.

  - type: input
    id: doc_section
    attributes:
      label: " Secci贸n / Archivo"
      description: "Archivo o lugar donde ocurre el problema (ej: README.md, /docs/uso.md, src/pages/about.md)."
      placeholder: "Ej: README.md"
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: " Descripci贸n"
      description: "Qu茅 est谩 mal o qu茅 falta (s茅 concreto)."
      placeholder: "Ej: El ejemplo de instalaci贸n est谩 desactualizado y falla con npm@9."
      render: markdown
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: " Propuesta de mejora (opcional)"
      description: "Si tienes una sugerencia concreta, p.ej. fragmento de texto o correcci贸n, p茅gala aqu铆."
      placeholder: "Ej: Reemplazar el paso 'npm install' por 'pnpm install' y a帽adir nota sobre Node 18+."
      render: markdown

  - type: dropdown
    id: type_of_doc_issue
    attributes:
      label: " Tipo"
      options:
        - Error factual
        - Falta de ejemplo
        - Texto confuso
        - Actualizaci贸n requerida
        - Otro
    validations:
      required: true

  - type: textarea
    id: proof
    attributes:
      label: " Evidencia (opcional)"
      description: "Capturas, enlaces o snippets que ayuden a reproducir o ilustrar el problema."
      placeholder: "Capturas o enlaces..."
      render: markdown

  - type: checkboxes
    id: checks
    attributes:
      label: "锔 Confirmaci贸n"
      options:
        - label: "He buscado si ya existe este issue."
          required: true
