name: "🚀 Propuesta de feature"
description: "Sugerir una nueva característica o mejora para el proyecto."
title: "[🚀] Propuesta: <título breve de la propuesta>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomarte el tiempo de proponer una mejora 🙌  
        Por favor completa la siguiente información para que podamos evaluar la propuesta.

  - type: textarea
    id: feature-description
    attributes:
      label: 📌 Descripción de la mejora
      description: Explica claramente qué funcionalidad o mejora propones.
      placeholder: "Quisiera añadir soporte para..."
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 🤔 Motivación
      description: ¿Qué problema resuelve esta mejora? ¿Por qué sería útil?
      placeholder: "Esto permitiría..."
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: 🛠 Ideas de implementación
      description: Si tienes ideas sobre cómo implementarlo, ponlas aquí.
      placeholder: "Podría implementarse creando un módulo..."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: ✔ Checklist
      description: Confirma lo siguiente antes de enviar:
      options:
        - label: Verifiqué que esta mejora no existe ya en issues.
          required: true
        - label: La mejora está alineada con la visión del proyecto.
          required: true
